services:

  redis:
    image: redis:alpine
    container_name: redis_container
    ports:
    - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    env_file:
      - .env
  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/posgresql/data
    container_name: postgres_db
    env_file:
      - .env
  
  web:
    build: 
      context: .
    volumes:
      - .:/trader
    ports:
      - 8000:8000
    image: trader:trader
    container_name: trader_web
    environment:
      RUN_ENTRYPOINT: "true"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  celery_worker:
      build: .
      container_name: trader_celery_worker
      command: celery -A trader worker --loglevel=info
      volumes:
      - .:/trader
      #environment:
      #  RUN_MIGRATIONS: "false"  # Este servicio no ejecuta migraciones
      depends_on:
        - redis
        - web
        - db
      env_file:
        - .env

  celery_beat:
      build: .
      container_name: trader_celery_beat
      command: celery -A trader beat --loglevel=info
      depends_on:
        - redis
        - web
        - celery_worker
      env_file:
        - .env    

  ws_listener:
    build: .
    container_name: ws_listener
    command: python realtime/ws_listener.py
    depends_on:
      - redis
      - db
      - web
      - celery_beat
    env_file:
      - .env