# Generated by Django 5.1 on 2024-12-24 00:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, unique=True)),
                ('base_asset', models.CharField(max_length=10)),
                ('quote_asset', models.CharField(max_length=10)),
                ('server_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], default='BUY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('symbol', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.symbol')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='dashboard.symbol')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['symbol', 'timestamp'], name='dashboard_h_symbol__635891_idx')],
            },
        ),
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(blank=True, max_length=200, null=True)),
                ('profit', models.DecimalField(decimal_places=10, max_digits=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('symbol_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_symbol_1', to='dashboard.symbol')),
                ('symbol_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_symbol_2', to='dashboard.symbol')),
                ('symbol_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_symbol_3', to='dashboard.symbol')),
            ],
            options={
                'indexes': [models.Index(fields=['symbol_1', 'symbol_2', 'symbol_3'], name='dashboard_a_symbol__86020d_idx'), models.Index(fields=['detected_at'], name='dashboard_a_detecte_6a1a49_idx')],
                'unique_together': {('symbol_1', 'symbol_2', 'symbol_3', 'detected_at')},
            },
        ),
    ]
