# Generated by Django 5.1 on 2024-12-20 17:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_currency', models.CharField(max_length=10)),
                ('quote_currency', models.CharField(max_length=10)),
                ('exchange', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], default='BUY', max_length=20)),
                ('amount', models.DecimalField(decimal_places=10, max_digits=20)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('fee', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('market_pair', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.marketpair')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.DecimalField(decimal_places=10, max_digits=20)),
                ('volume', models.DecimalField(blank=True, decimal_places=10, max_digits=20, null=True)),
                ('market_pair', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='dashboard.marketpair')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['market_pair', 'timestamp'], name='dashboard_h_market__35fc53_idx')],
            },
        ),
    ]
