# Generated by Django 5.1 on 2024-12-31 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route', models.CharField(max_length=255)),
                ('symbol_1', models.CharField(max_length=10)),
                ('symbol_2', models.CharField(max_length=10)),
                ('symbol_3', models.CharField(max_length=10)),
                ('detected_at', models.DateTimeField()),
            ],
        ),
    ]
