# Generated by Django 5.2 on 2025-04-19 17:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oportunity',
            options={'ordering': ['-detected_at']},
        ),
        migrations.AlterField(
            model_name='oportunity',
            name='detected_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 36, 58, 907582, tzinfo=datetime.timezone.utc)),
        ),
    ]
