# Generated by Django 5.1 on 2024-12-24 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalprice',
            name='price',
            field=models.DecimalField(decimal_places=10, max_digits=25),
        ),
        migrations.AlterField(
            model_name='historicalprice',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=25, max_digits=50, null=True),
        ),
    ]
