# Generated by Django 5.1 on 2024-12-20 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArbitrageOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profit', models.DecimalField(decimal_places=10, max_digits=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('pair_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_pair_1', to='dashboard.marketpair')),
                ('pair_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_pair_2', to='dashboard.marketpair')),
                ('pair_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arbitrage_pair_3', to='dashboard.marketpair')),
            ],
        ),
    ]
