# Generated by Django 5.1 on 2024-12-25 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_historicalprice_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='opportunity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.arbitrageopportunity'),
        ),
    ]
