# Generated by Django 5.2 on 2025-04-19 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_oportunity_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='detected_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 38, 34, 409433, tzinfo=datetime.timezone.utc)),
        ),
    ]
