# Generated by Django 5.1 on 2024-12-21 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_arbitrageopportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='arbitrageopportunity',
            name='route',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
