# Generated by Django 5.2 on 2025-04-19 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_oportunity_detected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='detected_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 4, 19, 17, 45, 10, 546884, tzinfo=datetime.timezone.utc)),
        ),
    ]
