# Generated by Django 5.1 on 2024-12-26 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_transactionlog_opportunity'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactionlog',
            name='market_pair',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
