# Generated by Django 5.2 on 2025-04-19 17:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_oportunity_detected_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oportunity',
            name='detected_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
