# Generated by Django 5.2 on 2025-04-19 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_oportunity_detected_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('close', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
            ],
            options={
                'ordering': ['symbol', 'timestamp'],
                'unique_together': {('symbol', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='TradingSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('signal_type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['-timestamp'],
                'unique_together': {('symbol', 'timestamp', 'signal_type')},
            },
        ),
        migrations.DeleteModel(
            name='Oportunity',
        ),
    ]
