# Generated by Django 5.2 on 2025-04-20 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_historicalprice_tradingsignal_delete_oportunity'),
    ]

    operations = [
        migrations.CreateModel(
            name='BacktestRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('initial_usd', models.DecimalField(decimal_places=8, max_digits=20)),
                ('final_usd', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('side', models.CharField(choices=[('BUY', 'BUY'), ('SELL', 'SELL')], max_length=4)),
                ('price', models.DecimalField(decimal_places=8, max_digits=20)),
                ('qty', models.DecimalField(decimal_places=8, max_digits=20)),
                ('ts_signal', models.DateTimeField()),
                ('ts_fill', models.DateTimeField()),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.backtestrun')),
            ],
        ),
    ]
